import Container from './components/Container';
import I from './components/I';
import Loader from './components/Loader';
import Main from './components/Main';
import Modal from './components/Modal';
import Strong from './components/Strong';
import U from './components/U';
// import useSnack from './snackBar/useSnack';
// import SnackBarContext from './snackBar/SnackBarContext';
// import SnackBar from './snackBar/SnackBar';
export { Container, Loader, Strong, I, U, Main, Modal };
